### ISSUE TITLE
Freezes on scenes larger than the train scene

### ISSUE THREAD

**Issue by hybridherbst** [quadjr/aframe-gaussian-splatting#1]
I tried the code with this model: https://lumalabs.ai/capture/c6f09528-f758-45c7-a92a-4af38067e266 (direct download link: https://drive.google.com/file/d/1p_eveZ66JM7TCKF2swDv1zctzIRo05uK/view?usp=sharing), which works fine in the original antimatter viewer when dropped: https://antimatter15.com/splat/
This viewer also works fine with the file: https://github.com/mkkellogg/GaussianSplats3D

However, when running it with the a-frame viewer component code, everything freezes my machine (M2 Mac) to a halt, and I have to kill the browser process. Would be curious if you get different results and/or have an idea what the reason may be.

**Comment by quadjr** [comment]
Thank you for using this component. At the moment, it only supports the 'splat' file format used in antimatter15's implementation and does not support the 'ply' format. To convert a 'ply' file to 'splat', drag and drop the 'ply' file into antimatter15's viewer and then download the 'splat' file.

I will be adding support for the 'ply' format this weekend. Please bear with me for a short while.

**Comment by quadjr** [comment]
I have added support for the .ply format. Please check it! [7642b06](https://github.com/quadjr/aframe-gaussian-splatting/commit/7642b06ff7052cd06d53da18218b5c1d51f09600)
