### ISSUE TITLE
Wanna join us on Discord?

### ISSUE THREAD

**Issue by dmarcos** [quadjr/aframe-gaussian-splatting#13]
Great work. We've been having a lot of fun with your component. There's parallel work and great ideas for features and improvements that might make sense to submit here. Would you like to join the chat on the [WebXR Discord](https://discord.gg/RCKnVV2a) #a-frame channel?

**Comment by quadjr** [comment]
Sounds great. I've joined the channel.
I'll check the threads in the Discord channel later because I have other commitments during the day.

**Comment by dmarcos** [comment]
@quadjr you have a twitter / x account I can mention?

**Comment by hybridherbst** [comment]
@dmarcos it's https://twitter.com/quadjr
