### ISSUE TITLE
Sorting looks incorrect for vertical axis

### ISSUE THREAD

**Issue by hybridherbst** [quadjr/aframe-gaussian-splatting#2]
Seems while sorting is fine in the horizontal axis, it's incorrect in the vertical axis:
https://github.com/quadjr/aframe-gaussian-splatting/assets/2693840/d0330b01-9728-49dc-938b-5955be10b29e
(same with the train scene)

**Comment by quadjr** [comment]
Thank you for your report. It looks strange.
Could you share the HTML code?

**Comment by hybridherbst** [comment]
Haven't changed anything so far!

**Comment by hybridherbst** [comment]
I think the only difference is that in your sample I can't rotate the camera so that it looks from above.

To repro, you can set position="0 -1.5 0" and use my .ply file;
then rotate around the scene:

https://github.com/quadjr/aframe-gaussian-splatting/assets/2693840/7fec21f0-aace-497a-9cc8-6f3d9882561f

**Comment by quadjr** [comment]
Thanks. I've reproduced the issue. I'll fix it later. The coordinates for AFrame and Gaussian Splatting are different, which is a bit confusing.

**Comment by quadjr** [comment]
I've fixed it! 
30985bf

**Comment by hybridherbst** [comment]
Wonderful! Thank you :)
