### ISSUE TITLE
2 fps on Quest 2

### ISSUE THREAD

**Issue by electrum-bowie** [quadjr/aframe-gaussian-splatting#7]
You are the best for creating this, I'm sure you'll will find a solution for optimisation. Good luck.

**Comment by electrum-bowie** [comment]
now getting 6-7 fps on Quest 2, you'll get there no problem ! @quadjr

**Comment by electrum-bowie** [comment]
30 fps when not looking at the train
Awesome!

**Comment by quadjr** [comment]
Continue improvements on #3.
