### ISSUE TITLE
how to load ply splats?

### ISSUE THREAD

**Issue by electrum-bowie** [quadjr/aframe-gaussian-splatting#8]
i tried opening a ply gaussian splat file exported from luma ai (lumalabs.ai)
and i'm getting this:

Uncaught (in promise) RangeError: byte length of Float32Array should be a multiple of 4
    at new Float32Array (<anonymous>)

Thanks, You're the best <3

**Comment by quadjr** [comment]
Is it possible to share the ply file?

**Comment by electrum-bowie** [comment]
yessir !

https://drive.google.com/file/d/1fYGZz2g0oSl_YPcQvKY8AAvaLWZcYdi3/view?usp=sharing

**Comment by electrum-bowie** [comment]
i'd love to talk to you privately about something in regard to this masterpiece,
do you have discord or any sort of way of communication?
i'm 
electrumbowie
or
Electrum#2787
on discord !
Thanks <3

**Comment by quadjr** [comment]
I couldn't download the file. Do I have permission to download it?

**Comment by electrum-bowie** [comment]
![image](https://github.com/quadjr/aframe-gaussian-splatting/assets/88616437/cffbf5af-423f-4297-a753-a7ae2fd6bdd5)
are you logged in on your browser to google?

**Comment by quadjr** [comment]
I'm not using discord. Are you using X account?
https://twitter.com/quadjr

**Comment by quadjr** [comment]
I logged in google. There is no download link. Just a "Unable to preview" message.
<img width="1434" alt="スクリーンショット 2023-10-12 0 26 30" src="https://github.com/quadjr/aframe-gaussian-splatting/assets/11469775/9a1d10ba-0656-42e1-978b-ca5f996b2784">

**Comment by electrum-bowie** [comment]
okay, no worries i'll make another link,
also, my twitter/x user:
@TheProBot

**Comment by electrum-bowie** [comment]
does this work?
https://cdn-luma.com/a54cfe380de47d7ef9e32f2ec04294784462c90a94e544c53cd8b7deb8965816/Crang_environment_gaussian_splatting_point_cloud.ply.zip

**Comment by quadjr** [comment]
Yah, I got it. I will check it tomorrow.

**Comment by quadjr** [comment]
@electrum-bowie 
Your data opened without any issues.
Could you specify your system environment?
I'm using Safari 16.6 and Chrome 117.0.5938.149 on Mac OS 13.5.1.

**Comment by electrum-bowie** [comment]
I use Microsoft edge 
Can you test if it works on the o oculus browser?

**Comment by electrum-bowie** [comment]
Also @quadjr how do you reference the ply file more easily instead of making a direct url link to it?

**Comment by quadjr** [comment]
It opens without any issues in the Quest browser on Quest3.
Here's my HTML.
How do you specify the .ply file?

```
<!DOCTYPE html>
<html>
  <head>
    <script src="https://aframe.io/releases/1.4.2/aframe.min.js"></script>
    <script src="index.js"></script>
  </head>
  <body>
    <a-scene renderer="antialias: false" stats>
      <a-entity position="0 1.6 -2.0" animation="property: rotation; to: 0 360 0; dur: 10000; easing: linear; loop: true">
        <a-sphere position="0 0 0.5" radius="0.5" color="#EF2D5E"></a-sphere>
        <a-sphere position="0 0 -0.5" radius="0.5" color="#EF2D5E"></a-sphere>
      </a-entity>
      <a-entity gaussian_splatting="src: gaussian_splatting_point_cloud.ply;" rotation="0 0 0" position="0 1.5 -2"></a-entity>
    </a-scene>
  </body>
</html>

```

**Comment by electrum-bowie** [comment]
oh thanks, i  uploaded it do huggingface and referenced that link in the html
i'm new to WebXR Development, sorry, i'll try it now!

**Comment by electrum-bowie** [comment]
![image](https://github.com/quadjr/aframe-gaussian-splatting/assets/88616437/ebadb8e7-7c34-43ad-9e3c-f70e2989992d)
still getting it on M-Edge.. :(
should i try with chrome?

**Comment by electrum-bowie** [comment]
![image](https://github.com/quadjr/aframe-gaussian-splatting/assets/88616437/e3c4af77-e235-4e8c-b254-2c94d589b64c)

**Comment by electrum-bowie** [comment]
same on chrome:

![image](https://github.com/quadjr/aframe-gaussian-splatting/assets/88616437/1aaa3f1d-eb9c-4b78-b661-e3ea47003f54)

**Comment by electrum-bowie** [comment]
<a-entity gaussian_splatting="src: gaussian_splatting_point_cloud.ply;" rotation="0 0 0" position="0 1.5 -2"></a-entity>

**Comment by electrum-bowie** [comment]
let me check something..
be right back

**Comment by quadjr** [comment]
The file size of gaussian_splatting_point_cloud.ply differs from the one you shared.
Are you using a different .ply file?

**Comment by electrum-bowie** [comment]
i think they're the same in terms of byte_length and parameters
also i think it's because the ply file has to be inside the repo i forked from you since i'm running this on git pages

**Comment by quadjr** [comment]
> ![image](https://user-images.githubusercontent.com/88616437/274603857-ebadb8e7-7c34-43ad-9e3c-f70e2989992d.png)
> still getting it on M-Edge.. :(
> should i try with chrome?

Oops, the log says the file cannot be found.
Have you set up and started a web server?

**Comment by quadjr** [comment]
huggingface is also ok.

**Comment by electrum-bowie** [comment]
got it to work, Thanks <3
